/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.wicia.projector.gui.windows.menu;

import java.awt.EventQueue;
import org.springframework.context.ApplicationContext;
import pl.wicia.projector.gui.windows.patterns.WindowAddPattern;
import pl.wicia.projector.gui.windows.workshops.WindowAddWorkshop;
import pl.wicia.projector.spring.contexts.ContextSettings;
import pl.wicia.projector.common.settings.AppSettings;
import pl.wicia.projector.common.settings.AppSettings.PropertyName;

/**
 *
 * @author Michał 'Wicia' Wietecha
 */
public class WindowMenu extends javax.swing.JFrame {

    /**
     * Creates new form WindowAddWorkshop
     */
    public WindowMenu() {
        this.initComponents();
        this.fillComponents();
    }
    
    private void fillComponents(){
        AppSettings settings = ContextSettings.getAppSettings();
        this.initLabelWorkshopName(settings);
    }
    
    private void initLabelWorkshopName(AppSettings s){
        Object value = s.getPropertyValue(PropertyName.WorkshopName);
        if(value != null){
            this.labelWorkshopName.setText(value.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonAddWorkshop = new javax.swing.JButton();
        buttonAddPatternElement = new javax.swing.JButton();
        labelWorkshopName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buttonModifyWorkshop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        buttonAddWorkshop.setBackground(new java.awt.Color(255, 102, 0));
        buttonAddWorkshop.setText("Dodawanie warsztatu");
        buttonAddWorkshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddWorkshopActionPerformed(evt);
            }
        });

        buttonAddPatternElement.setBackground(new java.awt.Color(255, 102, 0));
        buttonAddPatternElement.setText("Dodawanie wzorców");
        buttonAddPatternElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPatternElementActionPerformed(evt);
            }
        });

        labelWorkshopName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelWorkshopName.setForeground(new java.awt.Color(0, 0, 0));
        labelWorkshopName.setText("wewr");

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Zmień");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonModifyWorkshop.setBackground(new java.awt.Color(255, 102, 0));
        buttonModifyWorkshop.setText("Modyfikuj warsztat");
        buttonModifyWorkshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyWorkshopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelWorkshopName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonAddWorkshop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAddPatternElement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonModifyWorkshop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 223, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(buttonModifyWorkshop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAddPatternElement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAddWorkshop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWorkshopName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddWorkshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddWorkshopActionPerformed
        WindowAddWorkshop.open();
        this.dispose();
    }//GEN-LAST:event_buttonAddWorkshopActionPerformed
    
    private void buttonAddPatternElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPatternElementActionPerformed
        WindowAddPattern.open();
        this.dispose();
    }//GEN-LAST:event_buttonAddPatternElementActionPerformed

    private void buttonModifyWorkshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyWorkshopActionPerformed
        
    }//GEN-LAST:event_buttonModifyWorkshopActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        WindowChooseWorkshop.open();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //TODO: Jak to profesjonalnie zorganizować + refactroring innych metod tego typu
    public static void open(){
        EventQueue.invokeLater(() -> {
            WindowMenu window = new WindowMenu();
            window.setVisible(true);
            window.setLocationRelativeTo(null);
        });    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddPatternElement;
    private javax.swing.JButton buttonAddWorkshop;
    private javax.swing.JButton buttonModifyWorkshop;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelWorkshopName;
    // End of variables declaration//GEN-END:variables
}