/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.wicia.projector.gui.windows.menu;

import pl.wicia.projector.gui.windows.common.list.WindowChooseList;
import java.awt.EventQueue;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLayeredPane;
import pl.wicia.projector.database.entities.workshop.WorkshopEntity;

/**
 *
 * @author Michał 'Wicia' Wietecha
 */
public class WindowMenu extends javax.swing.JFrame {

    /**
     * Creates new form WindowAddWorkshop
     */
    public WindowMenu() {
        this.initComponents();
        this.initData();
    }
    
    private void initData(){
        this.layers.add(this.layerElements);
        this.layers.add(this.layerWorkshops);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelWorkshops = new javax.swing.JLabel();
        labelElements = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        layerWorkshops = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        buttonManage = new javax.swing.JButton();
        layerElements = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        labelWorkshops.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelWorkshops.setForeground(new java.awt.Color(0, 0, 0));
        labelWorkshops.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelWorkshops.setText("Warsztaty");
        labelWorkshops.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelWorkshops.setName("Warsztaty"); // NOI18N
        labelWorkshops.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelWorkshopsMouseEntered(evt);
            }
        });

        labelElements.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelElements.setForeground(new java.awt.Color(0, 0, 0));
        labelElements.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelElements.setText("Elementy");
        labelElements.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelElements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelElementsMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelWorkshops, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(labelElements, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWorkshops)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelElements)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        layerWorkshops.setName("WORKSHOPS"); // NOI18N

        buttonManage.setText("Zarządzaj");
        buttonManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(buttonManage)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(buttonManage)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        layerWorkshops.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layerWorkshopsLayout = new javax.swing.GroupLayout(layerWorkshops);
        layerWorkshops.setLayout(layerWorkshopsLayout);
        layerWorkshopsLayout.setHorizontalGroup(
            layerWorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layerWorkshopsLayout.setVerticalGroup(
            layerWorkshopsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layerElements.setName("ELEMENTS"); // NOI18N

        javax.swing.GroupLayout layerElementsLayout = new javax.swing.GroupLayout(layerElements);
        layerElements.setLayout(layerElementsLayout);
        layerElementsLayout.setHorizontalGroup(
            layerElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        layerElementsLayout.setVerticalGroup(
            layerElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(layerWorkshops)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(layerElements)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layerWorkshops, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(layerElements, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelWorkshopsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelWorkshopsMouseEntered
        this.showLayer(LayerName.WORKSHOPS);
    }//GEN-LAST:event_labelWorkshopsMouseEntered

    private void labelElementsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelElementsMouseEntered
        this.showLayer(LayerName.ELEMENTS);
    }//GEN-LAST:event_labelElementsMouseEntered

    private void buttonManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManageActionPerformed
        WindowChooseList.open(WorkshopEntity.class, this);
        this.dispose();
    }//GEN-LAST:event_buttonManageActionPerformed
        
    private void showLayer(LayerName name){
        layers.stream().forEach((JLayeredPane pane) -> {
            if(pane.getName().equals(name.toString())){
                pane.setVisible(Boolean.TRUE);
            }
            else{
                pane.setVisible(Boolean.FALSE);
            }
        });
    }
    
    //TODO: Jak to profesjonalnie zorganizować + refactroring innych metod tego typu
    public static void open(){
        EventQueue.invokeLater(() -> {
            WindowMenu window = new WindowMenu();
            window.setVisible(true);
            window.setLocationRelativeTo(null);
        });    
    }
    
    private enum LayerName {WORKSHOPS, ELEMENTS}
    private List<JLayeredPane> layers = new ArrayList<>();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonManage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelElements;
    private javax.swing.JLabel labelWorkshops;
    private javax.swing.JLayeredPane layerElements;
    private javax.swing.JLayeredPane layerWorkshops;
    // End of variables declaration//GEN-END:variables
}