/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.wicia.projector.gui.windows.workshops;

import java.awt.EventQueue;
import pl.wicia.projector.database.entities.workshop.WorkshopEntity;
import pl.wicia.projector.database.services.workshop.WorkshopService;
import pl.wicia.projector.gui.utils.dialogs.types.DialogError;
import pl.wicia.projector.gui.utils.dialogs.types.DialogInfo;
import pl.wicia.projector.gui.utils.dialogs.UtilsDialogs;
import pl.wicia.projector.common.exceptions.ExceptionDuplicateEntity;

/**
 *
 * @author Michał 'Wicia' Wietecha
 */
public class WindowAddWorkshop extends javax.swing.JFrame {

    /**
     * Creates new form WindowAddWorkshop
     */
    public WindowAddWorkshop() {
        this.initComponents();
        this.initDialogs();
    }
    
    private void initDialogs(){
        this.dialogs = new UtilsDialogs(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldWorkshopName = new javax.swing.JTextField();
        buttonAddWorkshop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nazwa warsztatu");

        buttonAddWorkshop.setBackground(new java.awt.Color(255, 102, 0));
        buttonAddWorkshop.setText("Dodaj");
        buttonAddWorkshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddWorkshopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldWorkshopName)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 290, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAddWorkshop)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldWorkshopName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAddWorkshop)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddWorkshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddWorkshopActionPerformed
        String workshopName = this.fieldWorkshopName.getText();
        if(!workshopName.isEmpty()){
            this.onAddingWorkshop(workshopName);
        }
        else{
            dialogs.show(new DialogError("Brak danych!", 
                    "Nazwa warsztatu jest pusta."));
        }
    }//GEN-LAST:event_buttonAddWorkshopActionPerformed

    private void onAddingWorkshop(String workshopName){
        WorkshopEntity entity = new WorkshopEntity(workshopName);
        try {
            // TODO Gdzie to ma być inicjalizowane i zapisywane?
            WorkshopService bean = WorkshopService.getService();
            bean.addWorkshop(entity);
            dialogs.show(new DialogInfo("Sukces!", 
                "Warsztat dodano do bazy danych.")); 
        } 
        catch (ExceptionDuplicateEntity ex){
            // TODO: gdzie umieszczać stringi?
            dialogs.show(new DialogError("Duplikat!", 
                    "Podany warsztat już istnieje w bazie"));
        }
        catch(Exception ex){
            dialogs.show(new DialogError("Błąd!", 
                    ex.getMessage()));
        }
    }
    
    //TODO: Jak to profesjonalnie zorganizować + refactroring innych metod tego typu
    public static void open(){
        EventQueue.invokeLater(() -> {
            WindowAddWorkshop window = new WindowAddWorkshop();
            window.setVisible(true);
            window.setLocationRelativeTo(null);
        });
    }
    
    private UtilsDialogs dialogs;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddWorkshop;
    private javax.swing.JTextField fieldWorkshopName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}